use_frameworks!

platform :ios, '8.0'

target 'HHTextFieldView_Example' do
  pod 'HHTextFieldView', :path => '../'

  target 'HHTextFieldView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
